name: Deploy Sphinx Documentation

on:
  push:
    branches:
      - main  # Adjust to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'  # Adjust to your Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_book_theme myst_parser  # Add your theme and extensions

    - name: Build Sphinx Documentation
      run: |
        sphinx-build -M html . _build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
        publish_branch: gh-pages  # Deploy to gh-pages branch

